# Generated by Django 4.0.4 on 2022-05-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='state_province',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
